// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7GV0H0DxqgQSXvo7Sx3Deef3TXEQD8Q',
    appId: '1:495835497484:android:ffe584933a9613e7015a29',
    messagingSenderId: '495835497484',
    projectId: 'we-chat-ae09f',
    storageBucket: 'we-chat-ae09f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMu4S7l-cj3E1J1RVmSILBO3bF-lA1gkI',
    appId: '1:495835497484:ios:5879af09a6ae0b8d015a29',
    messagingSenderId: '495835497484',
    projectId: 'we-chat-ae09f',
    storageBucket: 'we-chat-ae09f.appspot.com',
    androidClientId: '495835497484-92edhvg8abb0nr4nsbudnpc9brtstl7q.apps.googleusercontent.com',
    iosClientId: '495835497484-10sl5ph5cihg7jdu96cr1cs320i4iv8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
